server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: Zrx20040310!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 日志显示 SQL（可选）
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
